TaskManagerApp/Controllers/TaskHomesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskManagerApp.Data;
using TaskManagerApp.Models;

namespace TaskManagerApp.Controllers
{
    [Authorize]
    public class TaskHomesController : Controller
    {
        private readonly TaskManagerAppContext _context;
        private readonly UserManager<UserDetail> userMg;
        private readonly string? userId_;
        public TaskHomesController(TaskManagerAppContext context, UserManager<UserDetail> _User)
        {
            _context = context;
            userMg = _User;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.UserId = userMg.GetUserId(HttpContext.User);
            ViewBag.UserName = userMg.GetUserName(HttpContext.User);

            return View(await _context.TaskHome.Where(m => m.UserId == userMg.GetUserId(HttpContext.User)).ToListAsync());
        }
        public async Task<IActionResult> Details(int id)
        {
            ViewBag.UserId = userMg.GetUserId(HttpContext.User);
            if (id == null)
            {
                return NotFound();
            }

            var taskHome = await _context.TaskHome
                .FirstOrDefaultAsync(m => m.TaskId == id && m.UserId == userMg.GetUserId(HttpContext.User));
            if (taskHome == null)
            {
                return NotFound();
            }

            return View(taskHome);
        }
        public IActionResult Create()
        {
            ViewBag.UserId = userMg.GetUserId(HttpContext.User);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,TaskName,TaskDescription,Startdate,Deadline,TaskStatus")] TaskHome taskHome)
        {
            ViewBag.UserId = userMg.GetUserId(HttpContext.User);
            if (ModelState.IsValid)
            {
                _context.Add(taskHome);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(taskHome);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var userid = userMg.GetUserId(HttpContext.User);
            ViewBag.UserId = userid;
            if (id == null)
            {
                return NotFound();
            }

            var taskHome = await _context.TaskHome.FirstOrDefaultAsync(n => n.TaskId == id && n.UserId == userid);
            if (taskHome == null)
            {
                return NotFound();
            }
            return View(taskHome);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int TaskId, [Bind("TaskId,UserId,TaskName,TaskDescription,Startdate,Deadline,TaskStatusId")] TaskHome taskHome)
        {
            ViewBag.UserId = userMg.GetUserId(HttpContext.User);
            if (TaskId != taskHome.TaskId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taskHome);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskHomeExists(taskHome.TaskId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taskHome);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var userid = userMg.GetUserId(HttpContext.User);
            ViewBag.UserId = userid;
            if (id == null)
            {
                return NotFound();
            }

            var taskHome = await _context.TaskHome
                .FirstOrDefaultAsync(m => m.TaskId == id && m.UserId == userid);
            if (taskHome == null)
            {
                return NotFound();
            }

            return View(taskHome);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int TaskId)
        {
            var userid = userMg.GetUserId(HttpContext.User);
            ViewBag.UserId = userid;
            var taskHome = await _context.TaskHome.FirstOrDefaultAsync(m => m.TaskId == TaskId && m.UserId == userid);
            if (taskHome != null)
            {
                _context.TaskHome.Remove(taskHome);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool TaskHomeExists(int id)
        {
            ViewBag.UserId = userMg.GetUserId(HttpContext.User);
            return _context.TaskHome.Any(e => e.TaskId == id && e.UserId == userMg.GetUserId(HttpContext.User));
        }
        public void exceptionactn(Exception ex)
        {
            ViewBag.UserId = userMg.GetUserId(HttpContext.User);
            if (ex == null)
            {
                throw new ArgumentNullException(nameof(ex));
            }

        }
    }
}

TaskManagerApp/Controllers/UserDetailsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TaskManagerApp.Data;
using TaskManagerApp.Models;

namespace TaskManagerApp.Controllers
{
    [Authorize]
    public class UserDetailsController : Controller
    {
        private readonly UserManager<UserDetail> _userManager;
        private readonly SignInManager<UserDetail> _signInManager;
        private PasswordHasher<UserDetail> passwordHasher;
        public UserDetailsController(PasswordHasher<UserDetail> passwordhasher, UserManager<UserDetail> userManager,
                   SignInManager<UserDetail> signInManager, TaskManagerAppContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            passwordHasher = passwordhasher;
        }
        //get user info
        public async Task<IActionResult> Details()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User).ConfigureAwait(false);
            if (user == null)
            {
                RedirectToAction("Login");
            }
            //login functionality 
            return View(user);
        }

        [AllowAnonymous]
        public IActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Create(UserDetail appUser)
        {
            //register functionality  

            var user = new UserDetail
            {
                UserName = appUser.UserName,
                Email = appUser.Email,
                PasswordHash = appUser.PasswordHash
            };
            var result = await _userManager.CreateAsync(user, user.PasswordHash);
            if (result.Succeeded)
            {
                return RedirectToAction("LoginView", "Login");
            }
            else if (!result.Succeeded)
            {
                if (result.Errors.Count() > 0)
                {
                    throw new Exception(result.Errors?.FirstOrDefault()?.Description);
                }
            }
            return View(user);
        }

        //  GET: UserDetails/Edit/5
        public async Task<IActionResult> EditUserDetails()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User).ConfigureAwait(false);
            if (user == null)
            {
                RedirectToAction("Login");
            }
            //login functionality 
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUserDetails([Bind("Id,Email,UserName,PasswordHash")] UserDetail userDetail)
        {

            if (ModelState.IsValid)
            {
                UserDetail UpdatedUserData = await _userManager.FindByIdAsync(userDetail.Id);
                if (!string.IsNullOrEmpty(userDetail.Email))
                    UpdatedUserData.Email = userDetail.Email;
                if (!string.IsNullOrEmpty(userDetail.UserName))
                    UpdatedUserData.UserName = userDetail.UserName;
                if (!string.IsNullOrEmpty(userDetail.PasswordHash))
                    UpdatedUserData.PasswordHash = passwordHasher.HashPassword(userDetail, userDetail.PasswordHash);

                var result = await _userManager.UpdateAsync(UpdatedUserData);
                if (result.Succeeded)
                {
                    HttpContext.Session.SetString("userName", UpdatedUserData.UserName);
                    HttpContext.Session.SetString("Email", UpdatedUserData.Email);
                    return View(UpdatedUserData);
                }
                else
                    return Content("Error Occured!!");

            }
            return View(userDetail);
        }
    }
}

TaskManagerApp/Views/Shared/UserPartialVw.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@model TaskManagerApp.Models.UserDetail

@{
    ViewData["Title"] = "User Details";
}

<h1>Details</h1>

<div>
    <h4>User Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a href="@HttpContextAccessor.HttpContext.Request.Headers["Referer"].ToString()">Back</a>
</div>

TaskManagerApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagerApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagerApp.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="TaskHomes" asp-action="Index">The Task Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaskHomes" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaskHomes" asp-action="Create">Create New Task</a>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">

                                <img id="UserProPic" class="dropbtn" src=" /images/profpic.png">
                                <div class="dropdown-content">
                                    <a class="UserProPicOpt nav-link" asp-area="" asp-controller="UserDetails" asp-action="EditUserDetails">@HttpContextAccessor.HttpContext.Session.GetString("userName")</a>
                                    <a class="UserProPicOpt nav-link" asp-area="" asp-controller="Login" asp-action="LogOut">Logout</a>
                                </div>
                                </img>
                            </div>

                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <h1>The Task Manager</h1>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagerApp/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagerApp.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">The Task Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


            </div>
        </nav>
    </header>
    <div class="container LayoutbodyContent" style="background-color:black;color:white">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        <div class="container">
            <h1>The Task Manager</h1>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>